### ISSUE TITLE
Hi there quick question about installation of pip modules

### ISSUE THREAD

**Issue by wildaces215** [nabilkrs/python#1]
Can you tell me if I were to use this module where the modules come from pypi or pip?

**Comment by MCTRACO** [comment]
Actually, I think pip is a tool that installs packages form pypi, so pip is not actually a repository o modules , but pypi is

**Comment by nabilkrs** [comment]
Hey sir thank you for using Python package. Unfortunately this package will permanently discontinued and no longer useful. Thank you.
