### ISSUE TITLE
 Unhandled Exception: Exception: Error : Cannot open file

### ISSUE THREAD

**Issue by esraaabdrabo** [nabilkrs/python#3]
I downloaded the code example, but when I run it, it gives me the following error.

E/ion     (20257): ioctl c0044901 failed with code -1: Invalid argument
E/flutter (20257): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Error : Cannot open file
E/flutter (20257): #0      Python.execute
package:python/src/flutterpython.dart:65
E/flutter (20257): <asynchronous suspension>
E/flutter (20257): #1      _MyHomePageState.build.<anonymous closure>
package:example/main.dart:43
E/flutter (20257): <asynchronous suspension>
E/flutter (20257):
Application finished.
 
I didn't modify your code.
flutter doctor has no isuuse 
 Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)

**Comment by nabilkrs** [comment]
Hey sir thank you for using Python package. Unfortunately this package will permanently discontinued and no longer useful. Thank you.
