### ISSUE TITLE
Exception: Unexpected character (at chatacher 1) <!DOCTYPE html>

### ISSUE THREAD

**Issue by RMB8** [nabilkrs/python#4]
At the begging worked perfectly, but after 2 days an exception came out:
Error Occured FormatException: Unexpected character (at character 1)
<!DOCTYPE html> ^ )
(During these 2 days I didn't change anything, only the python code but it is not the problem because even if I use a empty file the error remains)

I try to fix it by searching in the forums but without success, so I printed the response.body to see why json.decode created an error and this is the result:
<!DOCTYPE html>
	<html>
 	  <head>
 		<meta name="viewport" content="width=device-width, initial-scale=1">
 		<meta charset="utf-8">
 		<title>Application Error</title>
 		<style media="screen">
 		  html,body,iframe {
 			margin: 0;
			padding: 0;
 		  }
 		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
 			width: 100%;
		height: 100%;
			border: 0;
 		  }
		</style>
	  </head>
 	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
 	  </body>
	</html>

If I go to the link inside iframe returns "Application Error".

I started to use flutter 3 moths ago so I'm a new user and I don't understand if this error is an error of my environment or of the heroku app

**Comment by nabilkrs** [comment]
Hey sir thank you for using Python package. Unfortunately this package will permanently discontinued and no longer useful. Thank you.
